# Generated by Django 2.1.15 on 2019-12-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('star', models.TextField()),
                ('time', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
